"""Identical deterministic V4 factor cover using bitset intersections/coverage.

Outcome-free CPU work shared by learned and strong classical priorities.
No factor recipe, weight tie, factor order, or actual scope is changed.
"""
from numbers import Integral

import numpy as np

from .core import Graph
from .v4_budgeted_recovery import NativeIntegerGraph


def conflict_clique_cover_fast(neighbors,weights):
    n=len(neighbors); neighbors=tuple(frozenset(row) for row in neighbors)
    if any(any(not isinstance(v,Integral) or isinstance(v,bool) or v<0 or v>=n or v==i
               for v in row) for i,row in enumerate(neighbors)):
        raise ValueError("Exact local conflict IDs required")
    if any(i not in neighbors[j] for i,row in enumerate(neighbors) for j in row):
        raise ValueError("Symmetric local conflicts required")
    weights=np.asarray(weights)
    if weights.shape!=(n,) or not np.all(np.isfinite(weights)) or np.any(weights<0):
        raise ValueError("Finite nonnegative cover-order weights required")
    return _validated_cover(neighbors,weights)


def _validated_cover(neighbors,weights):
    """Only validated immutable graph-local rows or the checked public API."""
    n=len(neighbors)
    ordering=sorted(range(n),key=lambda i:(-weights[i].item(),-len(neighbors[i]),i))
    rank={v:i for i,v in enumerate(ordering)}
    ranked_masks=[sum(1<<rank[v] for v in row) for row in neighbors]
    local_masks=[sum(1<<int(v) for v in row) for row in neighbors]
    covered=[0]*n; factors=set()
    for seed in ordering:
        allowed=ranked_masks[seed]
        if not allowed:continue
        clique=[seed]
        # Intersection only removes candidates: selecting the lowest rank bit
        # is exactly the original full ordered scan with skipped vertices.
        while allowed:
            bit=allowed&-allowed;vertex=ordering[bit.bit_length()-1]
            clique.append(vertex);allowed&=ranked_masks[vertex]
        factor=tuple(sorted(clique))
        if factor in factors:continue
        factors.add(factor)
        mask=sum(1<<int(v) for v in factor)
        # Same complete pair coverage, without constructing/rehashing O(k^2)
        # Python tuples for every repeated greedy clique.
        for vertex in factor:covered[vertex]|=mask^(1<<int(vertex))
    for vertex in range(n):
        uncovered=local_masks[vertex]&~covered[vertex]
        uncovered&=~((1<<(vertex+1))-1)
        while uncovered:
            bit=uncovered&-uncovered
            factors.add((vertex,bit.bit_length()-1));uncovered^=bit
    return tuple(sorted(factors))


def observable_factors_fast(graph,scope):
    ids=tuple(scope.replacements)
    if len(ids)!=len(set(ids)) or any(not isinstance(v,Integral) or isinstance(v,bool)
            or v<0 or v>=graph.n for v in ids):
        raise ValueError("Exact distinct recovery vertex IDs required")
    local={v:i for i,v in enumerate(ids)}
    neighbors=tuple(frozenset(local[u] for u in graph.adjacency[v] if u in local) for v in ids)
    weights=graph.weights[list(ids)]
    if not np.all(np.isfinite(weights)) or np.any(weights<0):
        raise ValueError("Finite nonnegative cover-order weights required")
    # These classes validate symmetric, loop-free immutable adjacency once;
    # local IDs below are generated by our dictionary, not arbitrary input.
    # Other duck graph implementations retain the public full validation path.
    cover=(_validated_cover(neighbors,weights) if isinstance(graph,(Graph,NativeIntegerGraph))
           else conflict_clique_cover_fast(neighbors,weights))
    factors=set(cover)
    for raw in scope.resource_cliques:
        if len(raw)!=len(set(raw)) or any(not isinstance(v,Integral) or isinstance(v,bool) or v not in local for v in raw):
            raise ValueError("Resource factor must be a distinct integer subset of this R")
        factor=tuple(sorted(local[v] for v in raw))
        if len(factor)<2 or any(v not in neighbors[u] for i,u in enumerate(factor) for v in factor[i+1:]):
            raise ValueError("Resource factor must be a genuine conflict clique")
        factors.add(factor)
    return neighbors,tuple(sorted(factors))
